networks:
  default:
    name: universal-resolver

services:
  uni-resolver-web:
    build:
      context: ./uni-resolver-web
      dockerfile: docker/Dockerfile
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
    environment:
      # Override default driver URLs if they are set in .env variables, otherwise
      # don't define the variables and let uni-resolver-web container use its default
      # set in application.yml.
      # See https://docs.docker.com/compose/compose-file/05-services/#environment
      uniresolver_web_driver_url_did_icon:
      uniresolver_web_driver_url_did_meta:

