server:
  servlet:
    contextPath: /
    mappings:
      properties: "/1.0/properties"
      resolve: "/1.0/identifiers"
      methods: "/1.0/methods"
      testIdentifiers: "/1.0/testIdentifiers"
      traits: "/1.0/traits"
  port: "8080"
  error:
    include-stacktrace: never
    include-message: never

spring:
  profiles:
    active: ${uniresolver_web_spring_profiles_active:default}

uniresolver:
  drivers:
    - pattern: "^(did:icon:.+)$"
      url: ${uniresolver_web_driver_url_did_icon:http://driver-did-icon:8080/}
      testIdentifiers:
        - did:icon:01:64aa0a2a479cb47afbf2d18d6f9f216bcdcbecdda27ccba3
    - pattern: "^(did:meta:gov:.+)$"
      url: ${uniresolver_web_driver_url_did_meta_gov:https://resolver.gov.metadium.com/1.0/identifiers/$1}
      testIdentifiers:
        - did:meta:gov:0000000000000000000000000000000000000000000000000000000000000001
    - pattern: "^(did:meta:.+)$"
      url: ${uniresolver_web_driver_url_did_meta:https://resolver.metadium.com/1.0/identifiers/$1}
      testIdentifiers:
        - did:meta:0000000000000000000000000000000000000000000000000000000000005e65

    - pattern: "^(did:empe:.+)$"
      url: ${uniresolver_web_driver_url_did_empe:http://driver-did-empe:8080/1.0/identifiers/$1}
      testIdentifiers:
        - did:empe:02bbae4a3c51a3134d0aa4bfe1e7ed19c6debe84
